#42 prepared nova code for smooth install
RonasIT/laravel-empty-project pull request #47
Opened 2023-03-17 15:28 UTC by Adil9994

2023-03-21 13:34 UTC, DenTray commented
@Adil9994 as discussed, we no need to install Nova to empty project, just prepare project to installation

2023-09-17 16:58 UTC, Goodmain commented
@DenTray I resolved conflicts. Please check again

2023-09-18 05:52 UTC, DenTray reviewed
@Goodmain could you please refine whether we should keep migration class and composer change here?

2023-09-19 15:40 UTC, Goodmain commented
@DenTray I removed migration and `auth` config file changes related to the `reset_passwords` table.

2023-09-25 03:28 UTC, DenTray requested changes

2023-09-25 03:28 UTC, DenTray commented on composer.json
> +  ],
```suggestion
```

2023-09-25 03:30 UTC, merged