#43: Updated linter and formatter packages
RonasIT/laravel-empty-project pull request #72
Opened 2024-02-25 12:53 UTC by ulin-evgeny

2024-02-26 06:39 UTC, DenTray requested changes

2024-02-26 06:39 UTC, DenTray commented on tlint.json
> +    "/app/bootstrap/app.php"
```suggestion
    "_ide_helper.php", 
    "_ide_helper_models.php",
    ".phpstorm.meta.php",
    ".php-cs-fixer.dist.php",
    "/app/Providers/DevDependenciesServiceProvider.php",
    "/app/public/index.php",
    "/app/Mails/BaseMail.php",
    "/app/bootstrap/app.php"
```

2024-02-27 12:20 UTC, ulin-evgeny commented
1. I disabled the MailableMethodsInBuild rule for tlint because tlint considers the file BaseMail.php invalid. But if you change the file as required tlint, then the changed area cannot be covered with tests - this is written in the comments in the file code (codeCoverageIgnore).
2. I disabled the AlphabeticalImports rule for tlint, because tlint considers function imports the same as class imports, which contradicts PSR-12, in which says that function imports should be separate.
3. To sort imports, you can replace tlint with PHP CS Fixer, but I did not do this because PHP CS Fixer also does not handle sorting well imports in classes where there is a function imports - for some reason, it separates some class imports with an empty string.

2024-02-29 15:38 UTC, DenTray requested changes

2024-02-29 15:38 UTC, DenTray commented on tlint.json
> +    "TrailingCommasOnArrays",
let's enable this rule, cause we decided to use trailing commas

2024-03-01 04:40 UTC, DenTray submitted a review, later dismissed

2024-03-04 09:38 UTC, DenTray approved these changes

2024-03-04 09:38 UTC, merged